In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
import numpy as np
data = pd.read_csv('gbm-data.csv')
data

,Activity,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,D1767,D1768,D1769,D1770,D1771,D1772,D1773,D1774,D1775,D1776
0,1,0.000000,0.497009,0.10,0.0,0.132956,0.678031,0.273166,0.585445,0.743663,...,0,0,0,0,0,0,0,0,0,0
1,1,0.366667,0.606291,0.05,0.0,0.111209,0.803455,0.106105,0.411754,0.836582,...,1,1,1,1,0,1,0,0,1,0
2,1,0.033300,0.480124,0.00,0.0,0.209791,0.610350,0.356453,0.517720,0.679051,...,0,0,0,0,0,0,0,0,0,0
3,1,0.000000,0.538825,0.00,0.5,0.196344,0.724230,0.235606,0.288764,0.805110,...,0,0,0,0,0,0,0,0,0,0
4,0,0.100000,0.517794,0.00,0.0,0.494734,0.781422,0.154361,0.303809,0.812646,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3746,1,0.033300,0.506409,0.10,0.0,0.209887,0.633426,0.297659,0.376124,0.727093,...,0,0,0,0,0,0,0,0,0,0
3747,1,0.133333,0.651023,0.15,0.0,0.151154,0.766505,0.170876,0.404546,0.787935,...,0,0,1,0,1,0,1,0,0,0
3748,0,0.200000,0.520564,0.00,0.0,0.179949,0.768785,0.177341,0.471179,0.872241,...,0,0,0,0,0,0,0,0,0,0
3749,1,0.100000,0.765646,0.00,0.0,0.536954,0.634936,0.342713,0.447162,0.672689,...,0,0,0,0,0,0,0,0,0,0
3750,0,0.133333,0.533952,0.00,0.0,0.347966,0.757971,0.230667,0.272652,0.854116,...,0,0,0,0,0,0,0,0,0,0

In [2]:
y = data['Activity']
y

0       1
1       1
2       1
3       1
4       0
       ..
3746    1
3747    1
3748    0
3749    1
3750    0
Name: Activity, Length: 3751, dtype: int64

In [3]:
X = data[data.columns[1:]]
X

,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,...,D1767,D1768,D1769,D1770,D1771,D1772,D1773,D1774,D1775,D1776
0,0.000000,0.497009,0.10,0.0,0.132956,0.678031,0.273166,0.585445,0.743663,0.243144,...,0,0,0,0,0,0,0,0,0,0
1,0.366667,0.606291,0.05,0.0,0.111209,0.803455,0.106105,0.411754,0.836582,0.106480,...,1,1,1,1,0,1,0,0,1,0
2,0.033300,0.480124,0.00,0.0,0.209791,0.610350,0.356453,0.517720,0.679051,0.352308,...,0,0,0,0,0,0,0,0,0,0
3,0.000000,0.538825,0.00,0.5,0.196344,0.724230,0.235606,0.288764,0.805110,0.208989,...,0,0,0,0,0,0,0,0,0,0
4,0.100000,0.517794,0.00,0.0,0.494734,0.781422,0.154361,0.303809,0.812646,0.125177,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3746,0.033300,0.506409,0.10,0.0,0.209887,0.633426,0.297659,0.376124,0.727093,0.308163,...,0,0,0,0,0,0,0,0,0,0
3747,0.133333,0.651023,0.15,0.0,0.151154,0.766505,0.170876,0.404546,0.787935,0.192527,...,0,0,1,0,1,0,1,0,0,0
3748,0.200000,0.520564,0.00,0.0,0.179949,0.768785,0.177341,0.471179,0.872241,0.122132,...,0,0,0,0,0,0,0,0,0,0
3749,0.100000,0.765646,0.00,0.0,0.536954,0.634936,0.342713,0.447162,0.672689,0.372936,...,0,0,0,0,0,0,0,0,0,0
3750,0.133333,0.533952,0.00,0.0,0.347966,0.757971,0.230667,0.272652,0.854116,0.140316,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                      test_size=0.8, 
                                      random_state=241)

In [5]:
from sklearn.metrics import log_loss
data = pd.read_csv('gbm-data.csv')
X = data.drop('Activity', axis=1).values
y = data.Activity.values

# Разбиение на трэйн/тест
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.8, 
                                                    random_state=241)

# Создание и обучение модели
gb = GradientBoostingClassifier(n_estimators=250,
                                learning_rate=0.2,
                                verbose=True,
                                random_state=241)
gb.fit(X_train, y_train)

# Получение значений лосса по итерациям
test_loss = list()
for i, y_pred in enumerate(gb.staged_decision_function(X_test)):
    y_pred = 1.0 / (1.0 + np.exp(- y_pred))
    test_loss.append([i + 1, log_loss(y_test, y_pred)])
test_loss = pd.DataFrame(test_loss, columns=['iter','loss'])

# Извлечение значения минимального лосса
test_loss[test_loss.loss==test_loss.loss.min()]

      Iter       Train Loss   Remaining Time
         1           1.2613           13.71s
         2           1.1715           12.50s
         3           1.1009           12.95s
         4           1.0529           12.99s
         5           1.0130           13.15s
         6           0.9740           12.78s
         7           0.9475           12.65s
         8           0.9197           12.39s
         9           0.8979           12.72s
        10           0.8730           12.49s
        20           0.7207           12.01s
        30           0.6055           11.70s
        40           0.5244           11.36s
        50           0.4501           10.70s
        60           0.3908           10.10s
        70           0.3372            9.51s
        80           0.3009            8.98s
        90           0.2603            8.41s
       100           0.2327            7.90s
       200           0.0835            2.85s

    iter      loss
36    37  0.530165

In [6]:
clfs = RandomForestClassifier(n_estimators=37, random_state=241)
clfs.fit(X_train, y_train)
pred = clfs.predict_proba(X_test)
round(log_loss(y_test, pred),2)

0.54