In [1]:
import pandas
import math
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
import numpy as np
import warnings
from sklearn.model_selection import KFold
warnings.filterwarnings('ignore')
features = pandas.read_csv('./features.csv', index_col='match_id')
print(features.shape)
features.head()

(97230, 108)

,start_time,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,...,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time,duration,radiant_win,tower_status_radiant,tower_status_dire,barracks_status_radiant,barracks_status_dire
match_id,,,,,,,,,,,,,,,,,,,,,
0,1430198770,7,11,5,2098,1489,20,0,0,7,...,4,2,2,-52.0,2874,1,1796,0,51,0
1,1430220345,0,42,4,1188,1033,9,0,1,12,...,4,3,1,-5.0,2463,1,1974,0,63,1
2,1430227081,7,33,4,1319,1270,22,0,0,12,...,4,3,1,13.0,2130,0,0,1830,0,63
3,1430263531,1,29,4,1779,1056,14,0,0,5,...,4,2,0,27.0,1459,0,1920,2047,50,63
4,1430282290,7,13,4,1431,1090,8,1,0,8,...,3,3,0,-16.0,2449,0,4,1974,3,63

## GradientBoostingClassifier

In [2]:
for i in features.columns:
    print(i, " - ", sum(features[i] != features[i]))

start_time  -  0
lobby_type  -  0
r1_hero  -  0
r1_level  -  0
r1_xp  -  0
r1_gold  -  0
r1_lh  -  0
r1_kills  -  0
r1_deaths  -  0
r1_items  -  0
r2_hero  -  0
r2_level  -  0
r2_xp  -  0
r2_gold  -  0
r2_lh  -  0
r2_kills  -  0
r2_deaths  -  0
r2_items  -  0
r3_hero  -  0
r3_level  -  0
r3_xp  -  0
r3_gold  -  0
r3_lh  -  0
r3_kills  -  0
r3_deaths  -  0
r3_items  -  0
r4_hero  -  0
r4_level  -  0
r4_xp  -  0
r4_gold  -  0
r4_lh  -  0
r4_kills  -  0
r4_deaths  -  0
r4_items  -  0
r5_hero  -  0
r5_level  -  0
r5_xp  -  0
r5_gold  -  0
r5_lh  -  0
r5_kills  -  0
r5_deaths  -  0
r5_items  -  0
d1_hero  -  0
d1_level  -  0
d1_xp  -  0
d1_gold  -  0
d1_lh  -  0
d1_kills  -  0
d1_deaths  -  0
d1_items  -  0
d2_hero  -  0
d2_level  -  0
d2_xp  -  0
d2_gold  -  0
d2_lh  -  0
d2_kills  -  0
d2_deaths  -  0
d2_items  -  0
d3_hero  -  0
d3_level  -  0
d3_xp  -  0
d3_gold  -  0
d3_lh  -  0
d3_kills  -  0
d3_deaths  -  0
d3_items  -  0
d4_hero  -  0
d4_level  -  0
d4_xp  -  0
d4_gold  -  0
d4_lh  -  0
d4_kills  -  0
d4_deaths  -  0
d4_items  -  0
d5_hero  -  0
d5_level  -  0
d5_xp  -  0
d5_gold  -  0
d5_lh  -  0
d5_kills  -  0
d5_deaths  -  0
d5_items  -  0
first_blood_time  -  19553
first_blood_team  -  19553
first_blood_player1  -  19553
first_blood_player2  -  43987
radiant_bottle_time  -  15691
radiant_courier_time  -  692
radiant_flying_courier_time  -  27479
radiant_tpscroll_count  -  0
radiant_boots_count  -  0
radiant_ward_observer_count  -  0
radiant_ward_sentry_count  -  0
radiant_first_ward_time  -  1836
dire_bottle_time  -  16143
dire_courier_time  -  676
dire_flying_courier_time  -  26098
dire_tpscroll_count  -  0
dire_boots_count  -  0
dire_ward_observer_count  -  0
dire_ward_sentry_count  -  0
dire_first_ward_time  -  1826
duration  -  0
radiant_win  -  0
tower_status_radiant  -  0
tower_status_dire  -  0
barracks_status_radiant  -  0
barracks_status_dire  -  0

In [3]:
y = features['radiant_win']
y

match_id
0         1
1         1
2         0
3         0
4         0
         ..
114402    0
114403    1
114404    0
114405    0
114406    1
Name: radiant_win, Length: 97230, dtype: int64

In [4]:
X = features.copy()
del X['radiant_win']
X = X.fillna(0)

In [5]:
gb = GradientBoostingClassifier(n_estimators=30, random_state=241)
from sklearn.model_selection import KFold
kf = KFold(random_state = 42, shuffle = True)

In [6]:
from datetime import datetime
start_time = datetime.now()
quality = cross_val_score(gb, X, y, cv=kf, scoring='f1')
print(datetime.now() - start_time)
np.mean(quality)

0:02:25.864070

0.986866805458844

In [7]:
gb = GradientBoostingClassifier(n_estimators=40, random_state=241)
start_time = datetime.now()
quality = cross_val_score(gb, X, y, cv=kf, scoring='f1', n_jobs = -1)
print(datetime.now() - start_time)
np.mean(quality)

0:01:59.122496

0.9872070803763183

## Logistic

In [8]:
from sklearn.linear_model import LogisticRegression

In [20]:
lr = LogisticRegression()
start_time = datetime.now()
quality = cross_val_score(lr, X, y, cv=kf, scoring='f1')
print(datetime.now() - start_time)
np.mean(quality)

0:00:02.123189

0.6829123274631944

Як бачимо модель логістичної регресії працює на багато гірше, хоча і швидше.

In [18]:
import re
X_without_categories = X.copy()
all_cat = [r'r1', r'r2', r'r3', r'r4', r'r5', r'd1', r'd2', r'd3', r'd4', r'd5']
for j in all_cat:
    for i in X.columns:
        if re.match(j, i): del X_without_categories[i]
X_without_categories

,start_time,lobby_type,first_blood_time,first_blood_team,first_blood_player1,first_blood_player2,radiant_bottle_time,radiant_courier_time,radiant_flying_courier_time,radiant_tpscroll_count,...,dire_tpscroll_count,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time,duration,tower_status_radiant,tower_status_dire,barracks_status_radiant,barracks_status_dire
match_id,,,,,,,,,,,,,,,,,,,,,
0,1430198770,7,7.0,1.0,9.0,0.0,134.0,-80.0,244.0,2,...,3,4,2,2,-52.0,2874,1796,0,51,0
1,1430220345,0,54.0,1.0,7.0,0.0,173.0,-80.0,0.0,2,...,5,4,3,1,-5.0,2463,1974,0,63,1
2,1430227081,7,224.0,0.0,3.0,0.0,63.0,-82.0,0.0,2,...,3,4,3,1,13.0,2130,0,1830,0,63
3,1430263531,1,0.0,0.0,0.0,0.0,208.0,-75.0,0.0,0,...,0,4,2,0,27.0,1459,1920,2047,50,63
4,1430282290,7,-21.0,1.0,6.0,0.0,166.0,-81.0,181.0,1,...,6,3,3,0,-16.0,2449,4,1974,3,63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114402,1450265551,1,114.0,0.0,2.0,8.0,245.0,-86.0,211.0,5,...,3,4,3,0,-24.0,2032,1792,1975,48,63
114403,1450277704,0,174.0,1.0,9.0,4.0,139.0,-85.0,202.0,5,...,4,3,2,0,-17.0,1734,2038,6,63,3
114404,1450291848,1,108.0,0.0,3.0,5.0,43.0,-83.0,181.0,2,...,1,1,3,1,-15.0,2906,1796,1846,51,63
114405,1450292986,1,28.0,0.0,4.0,6.0,96.0,-78.0,205.0,6,...,5,3,3,1,-42.0,951,2039,2047,63,63
114406,1450313370,7,14.0,1.0,7.0,1.0,118.0,-83.0,250.0,2,...,5,3,2,0,-39.0,2086,1982,0,63,0

In [21]:
start_time = datetime.now()
quality = cross_val_score(lr, X_without_categories, y, cv=kf, scoring='f1')
print(datetime.now() - start_time)
np.mean(quality)

0:00:00.964861

0.6829123274631944

In [48]:
len(set(X['r1_hero']))

108

In [55]:
gb = GradientBoostingClassifier(n_estimators=40, random_state=241)
quality = cross_val_score(gb, X, y, cv=kf, scoring='f1', n_jobs = -1)
quality

array([0.98827139, 0.98723489, 0.98643883, 0.98689046, 0.98719984])

In [56]:
max(quality)

0.9882713911020933